export { default as drawToCanvas } from './components/drawToCanvas'
// export { default as exportSVG } from './components/exportSVG'
export { default as fill } from './components/fill'
export { default as path } from './components/path'
// export { default as point } from './components/point'
// export { default as rectangle } from './components/rectangle'
